// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE

import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as App$SparcelyUnreasonable from "./App.bs.js";

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, App$SparcelyUnreasonable.make(/* array */[])), "root");

var match = module.hot;

if (match == null) {
  console.log("We are not hot");
} else {
  match.accept();
}

export {
  
}
/*  Not a pure module */
